# Generated by Django 2.1.2 on 2019-03-31 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('create_record_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
